version: '3'

services:
  yslinear-node:
    build: ./yslinear-node-covid19
    environment:
      - NODE_ENV=production
    volumes:
      - yslinear-node-data:/usr/src/app
    ports:
      - "8084:8080"
    depends_on:
      - "go"
    networks:
      - frontend
      - backend
  hakkies-node:
    build: ./hakkies-node-covid19
    environment:
      - NODE_ENV=production
    volumes:
      - hakkies-node-data:/usr/src/app
    ports:
      - "8083:8080"
    depends_on:
      - "go"
    networks:
      - frontend
  go:
    build: ./go-covid19
    expose:
      - 8082
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      - "db"
    networks:
      - backend
    volumes:
      - go-data:/app
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - "db"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    networks:
      - backend
volumes:
    yslinear-node-data:
    hakkies-node-data:
    go-data:
    db-data:
    pgadmin-data:

networks:
  frontend:
  backend: