version: '3'

services:
  node:
    build: ./node-covid19
    environment:
      - TZ=Asia/Taipei
      - NODE_ENV=production
    volumes:
      - node-data:/usr/src/app
    ports:
      - "8091:8080"
    restart: unless-stopped
    depends_on:
      - "go"
    networks:
      - frontend
      - backend
  go:
    build: ./go-covid19
    expose:
      - 8082
    ports:
      - "8092:8082"
    restart: unless-stopped
    depends_on:
      - "db"
    networks:
      - backend
    environment:
      - TZ=Asia/Taipei
    volumes:
      - go-data:/app
  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      TZ: "Asia/Taipei"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - "db"
    environment:
      TZ: "Asia/Taipei"
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8093:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    networks:
      - backend
volumes:
    node-data:
    go-data:
    db-data:
    pgadmin-data:

networks:
  frontend:
  backend: